from plugins.bot.constants.text import CATEGORY_NAME_TPL

DEFAULT_NUM_ITEMS_ON_TEXT = 5
MAX_LENGTH_CATEGORY_NAME = 255 - len(CATEGORY_NAME_TPL) + 2
MAX_LENGTH_CATEGORY_DESC = 255
MAX_LENGTH_SOURCE_ALIAS = 100

FORMAT_TIMESTAMP = "%Y-%m-%d %H:%M %Z"
