from plugins.bot.constants.text import CONF_DEL_TEXT_TPL

# TITLE

SINGULAR_CLEANUP_TITLE = "Очистка текста"
SINGULAR_COMMON_CLEANUP_TITLE = f"Общая {SINGULAR_CLEANUP_TITLE.lower()}"

SINGULAR_CLEANUP_PATTERN_TITLE = "Паттерн очистки текста"
SINGULAR_COMMON_CLEANUP_PATTERN_TITLE = (
    f"Общий {SINGULAR_CLEANUP_PATTERN_TITLE.lower()}"
)

# TEXT

SINGULAR_CLEANUP_PATTERN_TEXT = SINGULAR_CLEANUP_PATTERN_TITLE.lower()
SINGULAR_COMMON_CLEANUP_PATTERN_TEXT = SINGULAR_COMMON_CLEANUP_PATTERN_TITLE.lower()

SOURCE_TEXT = "для источника {}"

# ACTION

ACTION_ENTER_PATTERN = "Введи паттерн"

# QUESTION

QUESTION_CONF_DEL = CONF_DEL_TEXT_TPL.format(SINGULAR_CLEANUP_PATTERN_TEXT)
