STATISTIC_FILTER_TITLE = "Статистика фильтрации за {} д."
STATISTIC_FILTER_COMMON_TITLE = f"Общая {STATISTIC_FILTER_TITLE.lower()}"
STATISTIC_FILTER_DATA_NOT_FOUND = "__Данные отсутствуют__"
STATISTIC_FILTER_TOP_10 = "**Топ-10**:\n{}"
STATISTIC_FILTER_ANTI_TOP_10 = "**Анти-топ-10**:\n{}"
STATISTIC_FILTER_LINE = "{amount}: /f_{id} {type} `{pattern}`"
