name: deploy

on:
  push:
    branches:
     - master
     - hotfix/*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          script_stop: true
          script: |
            systemctl stop tgbot
            cd tg_ch_aggregator/
            mv logs "logs_$(date +%Y-%m-%d_%H-%M-%S)"
            git reset --hard HEAD
            git pull

            git checkout ${{ github.ref.name }}

            yoyo apply --database postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost/${{ secrets.DB_NAME }}
            systemctl start tgbot
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.repository }} -> ${{ github.workflow }} успешно выполнен!
