name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.S1_HOST }}
          username: ${{ secrets.S1_USER }}
          key: ${{ secrets.S1_SSH_KEY }}
          script: |
            cd /home/tgbot/tg_ch_aggregator/
            git pull
            supervisorctl restart tgbot
